/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingfutsal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Thread.sleep;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author xatalie
 */
public class Utama extends javax.swing.JFrame {
    static Database database;
    static String nama,tgl,lap,kat1,kat2,sta;
    static int id,bking,sisa,tot;
    static String  rblapangan;
    Date date;
    static String status;

    /**
     * Creates new form Utama
     */
    public Utama() {
        initComponents();
        database = new Database();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        //get current date time with Date()
        date = new Date();
        tftanggal.setText(dateFormat.format(date));
        tftanggal.disable();
        tfsisa.disable();
        tftotal.disable();
        tabelBooking();
    }
    private void tabelBooking(){
        PreparedStatement ps;
        DefaultTableModel model = (DefaultTableModel) tpembayaran.getModel();
        
        try{
            ps = database.conn.prepareStatement("select * from tiket");
            ResultSet rs = ps.executeQuery();
            int no = 1;
            while(rs.next()){
                Object o[] = {
                    no++, 
                    rs.getString("id_t"),
                    rs.getString("nama"), 
                    rs.getString("tanggal"),
                    rs.getString("lapangan"),
                    rs.getString("kategori1"),
                    rs.getString("kategori2"),
                    rs.getInt("booking"),
                    rs.getInt("sisa"),
                    rs.getInt("total"),
                    rs.getString("status"),
                };
                model.addRow(o); 
            }     
        }catch (Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lnama = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        ltanggal = new javax.swing.JLabel();
        tftanggal = new javax.swing.JTextField();
        llapangan = new javax.swing.JLabel();
        rblapangan1 = new javax.swing.JRadioButton();
        rblapangan2 = new javax.swing.JRadioButton();
        lkategori = new javax.swing.JLabel();
        cbkategori1 = new javax.swing.JComboBox<>();
        cbkategori2 = new javax.swing.JComboBox<>();
        lbayar = new javax.swing.JLabel();
        tfbayar = new javax.swing.JTextField();
        lsisa = new javax.swing.JLabel();
        tfsisa = new javax.swing.JTextField();
        ltotal = new javax.swing.JLabel();
        tftotal = new javax.swing.JTextField();
        judul = new javax.swing.JLabel();
        lsubmit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backgrond1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        judul1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpembayaran = new javax.swing.JTable();
        tfgetid = new javax.swing.JTextField();
        judulid = new javax.swing.JLabel();
        linsert = new javax.swing.JLabel();
        lupdate = new javax.swing.JLabel();
        ldelete = new javax.swing.JLabel();
        backgrond2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vamos Futsal");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jPanel3.setLayout(null);

        lnama.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        lnama.setText("Nama");
        jPanel3.add(lnama);
        lnama.setBounds(350, 90, 41, 15);

        tfnama.setFont(new java.awt.Font("Century Schoolbook L", 0, 12)); // NOI18N
        jPanel3.add(tfnama);
        tfnama.setBounds(520, 80, 320, 30);

        ltanggal.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        ltanggal.setText("Tanggal");
        jPanel3.add(ltanggal);
        ltanggal.setBounds(350, 140, 70, 15);

        tftanggal.setFont(new java.awt.Font("Century Schoolbook L", 0, 12)); // NOI18N
        jPanel3.add(tftanggal);
        tftanggal.setBounds(520, 130, 320, 30);

        llapangan.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        llapangan.setText("Lapangan");
        jPanel3.add(llapangan);
        llapangan.setBounds(350, 190, 80, 15);

        rblapangan1.setFont(new java.awt.Font("Century Schoolbook L", 1, 12)); // NOI18N
        rblapangan1.setText("Lapangan 1");
        rblapangan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblapangan1ActionPerformed(evt);
            }
        });
        jPanel3.add(rblapangan1);
        rblapangan1.setBounds(520, 180, 120, 21);

        rblapangan2.setFont(new java.awt.Font("Century Schoolbook L", 1, 12)); // NOI18N
        rblapangan2.setText("Lapangan 2");
        rblapangan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblapangan2ActionPerformed(evt);
            }
        });
        jPanel3.add(rblapangan2);
        rblapangan2.setBounds(710, 180, 130, 21);

        lkategori.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        lkategori.setText("Kategori");
        jPanel3.add(lkategori);
        lkategori.setBounds(350, 240, 70, 15);

        cbkategori1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi-Siang", "Sore-Malam" }));
        jPanel3.add(cbkategori1);
        cbkategori1.setBounds(520, 230, 120, 24);

        cbkategori2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Week Day", "Week End" }));
        jPanel3.add(cbkategori2);
        cbkategori2.setBounds(710, 230, 130, 24);

        lbayar.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        lbayar.setText("Bayar Booking");
        jPanel3.add(lbayar);
        lbayar.setBounds(350, 290, 110, 15);

        tfbayar.setFont(new java.awt.Font("Century Schoolbook L", 0, 12)); // NOI18N
        jPanel3.add(tfbayar);
        tfbayar.setBounds(520, 280, 320, 30);

        lsisa.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        lsisa.setText("Sisa");
        jPanel3.add(lsisa);
        lsisa.setBounds(350, 340, 40, 15);

        tfsisa.setFont(new java.awt.Font("Century Schoolbook L", 0, 12)); // NOI18N
        jPanel3.add(tfsisa);
        tfsisa.setBounds(520, 330, 320, 30);

        ltotal.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        ltotal.setText("Total");
        ltotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ltotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltotalMouseClicked(evt);
            }
        });
        jPanel3.add(ltotal);
        ltotal.setBounds(350, 390, 60, 20);

        tftotal.setFont(new java.awt.Font("Century Schoolbook L", 0, 12)); // NOI18N
        jPanel3.add(tftotal);
        tftotal.setBounds(520, 380, 320, 30);

        judul.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        judul.setText("Booking Vamos Futsal");
        jPanel3.add(judul);
        judul.setBounds(350, 20, 220, 19);

        lsubmit.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N
        lsubmit.setText("Submit");
        lsubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsubmitMouseClicked(evt);
            }
        });
        jPanel3.add(lsubmit);
        lsubmit.setBounds(520, 430, 90, 30);

        jLabel1.setText("Info:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(40, 320, 32, 15);

        jLabel2.setText("Pagi-Siang & Week Day = Rp. 80.000");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 340, 270, 15);

        jLabel3.setText("Sore-Malam & Week Day = Rp. 100.000");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(40, 370, 280, 15);

        jLabel4.setText("Pagi-Siang & Week End = Rp. 120.000");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(40, 400, 270, 15);

        jLabel5.setText("Sore-Malam & Week End = Rp. 140.000");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(40, 430, 280, 15);

        backgrond1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background2.jpg"))); // NOI18N
        jPanel3.add(backgrond1);
        backgrond1.setBounds(0, 0, 860, 510);

        jTabbedPane2.addTab("Booking", jPanel3);

        jPanel4.setLayout(null);

        judul1.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        judul1.setText("Pembayaran Vamos Futsal");
        jPanel4.add(judul1);
        judul1.setBounds(310, 30, 270, 19);

        tpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "Nama", "Tanggal", "Lapangan", "Kategori 1", "Kategori 2", "Booking", "Sisa", "Total", "Status"
            }
        ));
        jScrollPane1.setViewportView(tpembayaran);
        if (tpembayaran.getColumnModel().getColumnCount() > 0) {
            tpembayaran.getColumnModel().getColumn(0).setMinWidth(30);
            tpembayaran.getColumnModel().getColumn(0).setPreferredWidth(1);
            tpembayaran.getColumnModel().getColumn(0).setMaxWidth(30);
            tpembayaran.getColumnModel().getColumn(1).setMinWidth(30);
            tpembayaran.getColumnModel().getColumn(1).setPreferredWidth(1);
            tpembayaran.getColumnModel().getColumn(1).setMaxWidth(30);
            tpembayaran.getColumnModel().getColumn(2).setPreferredWidth(10);
            tpembayaran.getColumnModel().getColumn(4).setPreferredWidth(10);
            tpembayaran.getColumnModel().getColumn(5).setPreferredWidth(10);
            tpembayaran.getColumnModel().getColumn(6).setPreferredWidth(10);
            tpembayaran.getColumnModel().getColumn(7).setPreferredWidth(5);
            tpembayaran.getColumnModel().getColumn(8).setPreferredWidth(1);
            tpembayaran.getColumnModel().getColumn(9).setPreferredWidth(1);
            tpembayaran.getColumnModel().getColumn(10).setPreferredWidth(1);
        }

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 840, 300);

        tfgetid.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        jPanel4.add(tfgetid);
        tfgetid.setBounds(610, 69, 240, 30);

        judulid.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        judulid.setText("Masukkan ID");
        jPanel4.add(judulid);
        judulid.setBounds(610, 50, 100, 15);

        linsert.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        linsert.setText("Insert");
        linsert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        linsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linsertMouseClicked(evt);
            }
        });
        jPanel4.add(linsert);
        linsert.setBounds(610, 110, 50, 20);

        lupdate.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        lupdate.setText("Update");
        lupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupdateMouseClicked(evt);
            }
        });
        jPanel4.add(lupdate);
        lupdate.setBounds(700, 110, 60, 19);

        ldelete.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        ldelete.setText("Delete");
        ldelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ldelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ldeleteMouseClicked(evt);
            }
        });
        jPanel4.add(ldelete);
        ldelete.setBounds(800, 110, 46, 19);

        backgrond2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background2.jpg"))); // NOI18N
        jPanel4.add(backgrond2);
        backgrond2.setBounds(0, 0, 860, 510);

        jTabbedPane2.addTab("Pembayaran", jPanel4);

        jPanel1.add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 860, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ltotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltotalMouseClicked
        if("Pagi-Siang".equals(cbkategori1.getModel().getSelectedItem().toString())&&"Week Day".equals(cbkategori2.getModel().getSelectedItem().toString())){
            tftotal.setText("80000");
            Integer bayar = Integer.parseInt(tfbayar.getText());
            Integer sisa;
            Integer total = Integer.parseInt(tftotal.getText());
            sisa = total - bayar;
            tfsisa.setText(sisa.toString());
        }else if("Sore-Malam".equals(cbkategori1.getModel().getSelectedItem().toString())&&"Week Day".equals(cbkategori2.getModel().getSelectedItem().toString())){
            tftotal.setText("100000");
            Integer bayar = Integer.parseInt(tfbayar.getText());
            Integer sisa;
            Integer total = Integer.parseInt(tftotal.getText());
            sisa = total - bayar;
            tfsisa.setText(sisa.toString());
        }else if("Pagi-Siang".equals(cbkategori1.getModel().getSelectedItem().toString())&&"Week End".equals(cbkategori2.getModel().getSelectedItem().toString())){
            tftotal.setText("120000");
            Integer bayar = Integer.parseInt(tfbayar.getText());
            Integer sisa;
            Integer total = Integer.parseInt(tftotal.getText());
            sisa = total - bayar;
            tfsisa.setText(sisa.toString());
        }else if("Sore-Malam".equals(cbkategori1.getModel().getSelectedItem().toString())&&"Week End".equals(cbkategori2.getModel().getSelectedItem().toString())){
            tftotal.setText("140000");
            Integer bayar = Integer.parseInt(tfbayar.getText());
            Integer sisa;
            Integer total = Integer.parseInt(tftotal.getText());
            sisa = total - bayar;
            tfsisa.setText(sisa.toString());
        }
        if(tfbayar.getText().equals(tftotal.getText())){
            status = "Lunas";
        }else{
            status= "Belum Lunas";
        }
    }//GEN-LAST:event_ltotalMouseClicked

    private void rblapangan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblapangan1ActionPerformed
        // TODO add your handling code here:
        if(rblapangan1.isSelected()){
            rblapangan2.setEnabled(false);
            rblapangan = rblapangan1.getText();
        }else if(!rblapangan1.isSelected()){
            rblapangan2.setEnabled(true);
        }else if(rblapangan1.isSelected()&&rblapangan2.isSelected()){
            JOptionPane.showMessageDialog(null, "Pilih salah satu");
        }
    }//GEN-LAST:event_rblapangan1ActionPerformed

    private void rblapangan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblapangan2ActionPerformed
        // TODO add your handling code here:
        if(rblapangan2.isSelected()){
            rblapangan1.setEnabled(false);
            rblapangan = rblapangan2.getText();
            
        }else if(!rblapangan2.isSelected()){
            rblapangan1.setEnabled(true);
        }else if(rblapangan1.isSelected()&&rblapangan2.isSelected()){
            JOptionPane.showMessageDialog(null, "Pilih salah satu");
        }
    }//GEN-LAST:event_rblapangan2ActionPerformed

    private void lsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsubmitMouseClicked
        // TODO add your handling code here:
        System.out.println(tfnama.getText()+tftanggal.getText()+rblapangan+cbkategori1.getModel().getSelectedItem().toString()+
                cbkategori2.getModel().getSelectedItem().toString()+Integer.parseInt(tfbayar.getText())+Integer.parseInt(tfsisa.getText())+
                Integer.parseInt(tftotal.getText()));
        
        try {
            
            String sql = "INSERT INTO tiket VALUES (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst;
            pst = database.conn.prepareStatement(sql);
            
            pst.setNull(1, java.sql.Types.INTEGER);
            pst.setString(2, tfnama.getText());
            pst.setString(3, tftanggal.getText());
            pst.setString(4, rblapangan);
            pst.setString(5, cbkategori1.getModel().getSelectedItem().toString());
            pst.setString(6, cbkategori2.getModel().getSelectedItem().toString());
            pst.setInt(7, Integer.parseInt(tfbayar.getText()));
            pst.setInt(8, Integer.parseInt(tfsisa.getText()));
            pst.setInt(9, Integer.parseInt(tftotal.getText()));
            pst.setString(10, status);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Input Berhasil");
            
            Utama utama = new Utama();
            utama.setVisible(true);
            utama.setLocationRelativeTo(null);
            
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
    }//GEN-LAST:event_lsubmitMouseClicked

    private void linsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linsertMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        Utama utama = new Utama();
        utama.setVisible(true);
        utama.setLocationRelativeTo(null);
    }//GEN-LAST:event_linsertMouseClicked

    private void lupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupdateMouseClicked
        // TODO add your handling code here:
        try{
            String sql = "select * from tiket where id_t=?";
            PreparedStatement pst;
            pst = database.conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(tfgetid.getText()));
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                Object o[] = {
                    id=Integer.parseInt(rs.getString("id_t")),
                    nama=rs.getString("nama"), 
                    tgl=rs.getString("tanggal"),
                    lap=rs.getString("lapangan"),
                    kat1=rs.getString("kategori1"),
                    kat2=rs.getString("kategori2"),
                    bking=rs.getInt("booking"),
                    sisa=rs.getInt("sisa"),
                    tot=rs.getInt("total"),
                    sta=rs.getString("status"),
                };
            
                
            }
            
            this.dispose();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
        
        
        Update u = new Update();
        u.setVisible(true);
        u.setLocationRelativeTo(null);
    }//GEN-LAST:event_lupdateMouseClicked

    private void ldeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ldeleteMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM tiket WHERE id_t=?";
            PreparedStatement pst;
            pst = database.conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(tfgetid.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete Berhasil");
            Utama utama = new Utama();
            utama.setVisible(true);
            utama.setLocationRelativeTo(null);
//            new Thread(){
//                public void run(){
//                    try{
//                        for(int i = 0;i<100;i++){
//                            System.err.println(i);
//                            sleep(50);
//                            prog.setValue(i);
//                        }
//                    }catch(Exception e){
//                        
//                    }
//                }
//              }.start();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
    }//GEN-LAST:event_ldeleteMouseClicked
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgrond1;
    private javax.swing.JLabel backgrond2;
    private javax.swing.JComboBox<String> cbkategori1;
    private javax.swing.JComboBox<String> cbkategori2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judulid;
    private javax.swing.JLabel lbayar;
    private javax.swing.JLabel ldelete;
    private javax.swing.JLabel linsert;
    private javax.swing.JLabel lkategori;
    private javax.swing.JLabel llapangan;
    private javax.swing.JLabel lnama;
    private javax.swing.JLabel lsisa;
    private javax.swing.JLabel lsubmit;
    private javax.swing.JLabel ltanggal;
    private javax.swing.JLabel ltotal;
    private javax.swing.JLabel lupdate;
    private javax.swing.JRadioButton rblapangan1;
    private javax.swing.JRadioButton rblapangan2;
    private javax.swing.JTextField tfbayar;
    private javax.swing.JTextField tfgetid;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfsisa;
    private javax.swing.JTextField tftanggal;
    private javax.swing.JTextField tftotal;
    private javax.swing.JTable tpembayaran;
    // End of variables declaration//GEN-END:variables
}
